query findMessages(
  $input: FindMessageInputDto!
  $queryParams: QueryFilterDto!
) {
  findMessages(input: $input, queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      message
      inboxId
      senderEmail
      receiverEmail
      senderName
      receiverName
      isRead
      isFirstMessageOfTheDay
      replyToMessageId
      replySelectedMessageType
      replySelectedMessage
      replyToMessage {
        id
        senderEmail
        senderName
      }
      replySelectedFile {
        ...FileInputFragment
      }
      createdAt
      messageFiles {
        id
        file
        media
        link
        type
        messageId
        fileSize
        fileName
        fileType
        fileIndex
      }
    }
  }
}
