query getMessages($queryParams: MessageQueryFilter!) {
  getMessages(queryParams: $queryParams) {
    meta {
      ...MetaFragment
    }
    items {
      id
      message
      inboxId
      senderEmail
      receiverEmail
      senderName
      receiverName
      isRead
      replyToMessageId
      replySelectedMessageType
      replySelectedMessage
      replyToMessage {
        id
        senderEmail
        senderName
      }
      replySelectedFile {
        ...FileInputFragment
      }
      createdAt
      messageFiles {
        id
        file
        media
        link
        type
        messageId
        fileSize
        fileName
        fileType
        fileIndex
      }
    }
  }
}
