query getTrackingDriver(
  $trackingDriverId: String!
  $allowExpiredLink: Boolean
) {
  getTrackingDriver(
    trackingDriverId: $trackingDriverId
    allowExpiredLink: $allowExpiredLink
  ) {
    id
    caseName
    placeOfDeparture
    placeOfArrival
    providerEmail
    departureName
    arrivalName
    arrivePhotoKey
    departurePhotoKey
    status
    transportId
  }
}
